// Generated by CoffeeScript 1.6.3
(function() {
  var Job, KUE_JOBS, kue, p, redis, _;

  p = require("commander");

  redis = require("redis");

  _ = require("underscore");

  kue = require('kue');

  Job = kue.Job;

  p.version('0.0.1').option('-p, --port <n>', 'redis service port').option('-h, --host [VALUE]', 'redis service host').parse(process.argv);

  kue.redis.createClient = function() {
    var client;
    client = redis.createClient(KUE_PORT, KUE_HOST);
    client.on("error", function(error) {
      return logger.error("[crawler_service::LocalRedisClient::on error] " + error);
    });
    client.on("reconnecting", function(info) {
      return logger.info("[crawler_service::LocalRedisClient::on reconnecting] reconnecting to datastore... delay:" + info.delay + ", attempt:" + info.attempt);
    });
    client.on("end", function() {
      console.error("[kue-sweeper::redis::on end] redis client end @ " + p.host + ":" + p.port);
    });
    client.on("ready", function() {
      console.log("[kue-sweeper::redis::on ready] kue client is ready to monitor redis server @ " + p.host + ":" + p.port);
    });
    return client;
  };

  KUE_JOBS = kue.createQueue();

  KUE_JOBS.on('job complete', function(id) {
    Job.get(id, function(err, job) {
      if (err != null) {
        logger.warn("[kue-sweeper::on job completed] fail to get job: " + id + ". error:" + err);
        return;
      }
      logger.log("[kue-sweeper::removeKueJob] job:" + job);
      if (!((job != null) && _.isFunction(job.remove))) {
        logger.error("[kue-sweeper::removeKueJob] bad argument, " + job);
        return;
      } else {
        job.remove;
      }
    });
  });

}).call(this);
